### ISSUE TITLE
Install/run dependencies

### ISSUE THREAD

**Issue by gerardbosch** [sudoRicheek/Image-Enhancer#3]
Hi there 👋

Python dependencies are not listed anywhere, no `requirements.txt` nor in the README. So with an out-of-the-box Python installation (MacOS or Linux) the command in the README `python run.py` does not work:

```console
❯ python run.py 
Traceback (most recent call last):
  File "/tmp/Image-Enhancer/run.py", line 1, in <module>
    from AppWindowQt import Ui_MainWindow
  File "/tmp/Image-Enhancer/AppWindowQt.py", line 2, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'
```

Also, the Python version is not specified.

In summary, a comprehensive installation/run description should be provided.

Cheers!!

**Comment by JeroenSteen** [comment]
Also run into this issue, also needed are: cv2 (opencv-python), tensorflow?

With tensorflow it gives this error:
ERROR: Could not install packages due to an OSError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden: 'c:\\python39\\Scripts\\pyrsa-decrypt.exe' -> 'c:\\python39\\Scripts\\pyrsa-decrypt.exe.deleteme'

**Comment by sophial05** [comment]
Also ran into this issue. Could you please provide a requirements.txt file? Thank you!!
